### ISSUE TITLE
Firebase structure

### ISSUE THREAD

**Issue by DK-Developer** [mrizwan18/FurnitAR#6]
what is the structure of firebase database

**Comment by mrizwan18** [comment]
So the database structure is as follows:

cart:
       id: id of the cart
       quantity: quantity of products
       user: userID
items:
         description:
         images: 
                     In case isAR is true, 0th index is a JPEG/PNG image to be 
                     displayed and 1st index is the google poly 3D model that is being rendered by the app 
                     using Sceneform.
                     In case if isAR is false, the array is of size 1 where 0th index is just a JPEG/PNG to be 
                     displayed 

         isAR:
         name:
         price:
         quantity:

purchase_history:
                            id: id of the cart
                            quantity: quantity of products
                            user: userID

**Comment by honguyen1608** [comment]
Pls share me your firebase structure photo

**Comment by mrizwan18** [comment]
![image](https://user-images.githubusercontent.com/34402664/80252428-aaf7ca80-8690-11ea-9ce0-f112f2d6b9cd.png)
![image](https://user-images.githubusercontent.com/34402664/80252483-c4991200-8690-11ea-898e-bc2a650917b5.png)
![image](https://user-images.githubusercontent.com/34402664/80252510-d4b0f180-8690-11ea-9953-bc64b7fbf9ba.png)
![image](https://user-images.githubusercontent.com/34402664/80252553-e72b2b00-8690-11ea-8201-ee8f27ab5f7f.png)

**Comment by hadat312** [comment]
How to replace your cloud firestore to my cloud firestore? thanks!
